### ISSUE TITLE
Title bar of maximized windows hidden by banner

### ISSUE THREAD

**Issue by abenson** [fcaviggia/classification-banner#10]
The title bars of maximized windows are obscured by the banner. Is there a way to have the banner block windows like on the Windows NetBanner, or is there a workaround for metacity (or something) to prevent this?

**Comment by fcaviggia** [comment]
I haven't found anything that works nicely. I'm not sure how to make it act like the panel bars, so I'll ask around Red Hat to see if anyone else has any ideas on how to make that work.

**Comment by 7ooL** [comment]
I have the same issue with our kickstart, I'm sure someone in the DoD is going to complain so a fix would be greatly appreciated.

**Comment by fcaviggia** [comment]
I'm not really finding any good answers to this issue. One idea I was looking at was, that if the window manager has transparency, using the opacity setting to allow a semi transparent banner. 

gtk.Window.set_opacity

    def set_opacity(opacity)

opacity :
	desired opacity, between 0 and 1.
Note

This method is available in PyGTK 2.12 and above.

Request the windowing system to make window partially transparent, with opacity 0 being fully transparent and 1 fully opaque. (Values of the opacity parameter are clamped to the [0,1] range.) On X11 this has any effect only on X screens with a compositing manager running. See gtk.Widget.is_composited(). On Windows it should work always.

Note that setting a window's opacity after the window has been shown causes it to flicker once on Windows.

**Comment by fcaviggia** [comment]
Okay, it doesn't appear that pygtk has a good method for making this work. I was looking at using the set_opacity to allow some transparency if the window manager supports it. Also, adding a feature like netbanner to use "Esc" to temporarily hide the banner for 10-15s.

**Comment by fcaviggia** [comment]
Added opacity - still trying to work out the hiding of the window for a temporary period of time...

**Comment by fcaviggia** [comment]
Added the ability to use ESC key to temporarily hide widow for 15 seconds. The window will reappear after that period of time.
