### ISSUE TITLE
Classification banner does not allow new windows to take focus  in GNOME 3

### ISSUE THREAD

**Issue by brun064** [fcaviggia/classification-banner#17]
Experienced on RHEL 7.2.

When the classification banner is running, new windows will open without focus.  
To recreate:
1) Log-in to RHEL and start classification banner
2) Right click on desktop and click "Open in Terminal"
3) Note that the focus is still on the desktop.  You cannot type into the terminal window unless you click on the new terminal window.
4) Kill the classification banner
5) Repeat step 2. 
6) Note that the window is in focus and you can immediately type into it without clicking.

This issue also prevents firefox from bringing new windows into focus.  If Firefox is running maximized and the user clicks on a link which opens a new window, the window is opened in the background and Gnome 3 shows a notification with message: Firefox Web Browser - "<window-name>" is ready.  This forces the user to click this annoying gnome 3 message to bring up the new window.

**Comment by brun064** [comment]
This behavior is only active when the top banner is present.

**Comment by fcaviggia** [comment]
Any ideas on how to fix this behavior?

**Comment by brun064** [comment]
I'm not sure how this behavior is even happening.  It's something odd with Gnome 3 and the way it likes to background the process until it's ready.  

I experimented by moving the top banner lower and lower until the issue no longer occurred.  Here is what I noticed.  If the bottom of the new window is below the top of the top banner, Gnome will background the window.  If the bottom of the new window is above the top banner, Gnome will display the new window.  So it's something to do with the top banner always being above the new window as Gnome 3 sees it in the "stack."

The latest version of "Steal My Focus" Gnome shell extension fixes this issue.  With the extension, everything seems to work as expected.  Closing, but feel free to re-open if you want to work on a built in solution.

https://extensions.gnome.org/extension/234/steal-my-focus/

**Comment by fcaviggia** [comment]
Perhaps a bug should be filed with the GNOME 3 developers - I haven't had a problem on any other Window Manager.

**Comment by brun064** [comment]
The issue is no doubt caused by GNOME 3's design and implementation.  It's possible that his was fixed in a later version of GNOME 3.  However, the path of least resistance seems to be using the above referenced shell extension.  Luckily, there is way to enable extensions for all users so the banner and extension can be deployed together without any user interaction to fix the issue.  

The alternative is to submit a bug to GNOME 3, argue the case for fixing it.  Wait for them to deploy the change in a future version of GNOME 3.  Then submit a bug against RHEL7 to Red Hat to back-stitch the fix into a future RHEL7 release and then wait for that.  To quote the poet Sweet Brown, "Aint nobody got time for that."

**Comment by fcaviggia** [comment]
That's probably a good bet.  Thanks for the Sweet Brown quote. :+1:
