### ISSUE TITLE
Virtual Box VM only shows in the middle of the screen

### ISSUE THREAD

**Issue by cmschube** [fcaviggia/classification-banner#19]
See attached... can help anyway I can. 

![image](https://cloud.githubusercontent.com/assets/5130724/22479853/ef9be60e-e7b4-11e6-8700-df907fb47648.png)

**Comment by fcaviggia** [comment]
I haven't tested it in MIR with Ubuntu as I've mainly developed it for Fedora/CentOS/RHEL - does the system have xrandr installed?

https://wiki.ubuntu.com/X/Config/Resolution#Dynamic_setup_with_xrandr

**Comment by cmschube** [comment]
Yes sir.. I looked through the code and that was the first thing I checked.. 

I then though that maybe the sizing in virtual box was causing the issue (the resolution was something like 1160x814), so I set it to an "easy" resolution (1280x1024), but no luck there.. 

![image](https://cloud.githubusercontent.com/assets/5130724/22528676/f13d2140-e899-11e6-93bb-e5da76db5dc2.png)

I've even tried to pass the resolution parameters as:

/usr/bin/classification-banner.py  -x 1280 -y 1024

but to no avail.. 

Interestingly enough, if I set the x to something less, the banner does scale down, but it's almost like it just ignores the y input.. 

![image](https://cloud.githubusercontent.com/assets/5130724/22528881/c4797be4-e89a-11e6-9020-7c78d0edcbe6.png)

**Comment by fcaviggia** [comment]
I'll have to download Ubuntu later and play with it.  I works pretty well in CentOS and Fedora.

**Comment by cmschube** [comment]
Sounds good.. I appreciate the responses thus far. Let me know if I can be of any help..

**Comment by wamacdonald89** [comment]
@cmschube I was able to get it to look correct by playing with the offsets.

(line 345) top.window.move(self.x_location, self.y_location+25)
(line 359) bottom.window.move(self.x_location, int(bottom.vres)-20)

I haven't tried with any other resolutions though.

**Comment by fcaviggia** [comment]
I've tried a few things on Ubuntu - this seems to be a problem with MIR rather than the python, since it seems to work fine on other Window Managers. You could use MATE or Cinnamon spins of Ubuntu and it will work just fine.  I guess the question for me is why would you do anything above Unclassified work on Ubuntu (Canonical is based out of South Africa and there is no DISA STIG for Ubuntu either).

**Comment by cmschube** [comment]
Yeah.. I'm with you with regards to Ubuntu. But our engineers use it, and
our DSS rep approves it, so I just need to make sure it's as configured as
can be... I'd much prefer to use RedHat for everything..

Thanks for checking into the issue for me. I appreciate the fact that you
didn't have to do it, but did it anyway. I'll do some digging on my end, if
I come up with anything, I'll let you know..

Thanks -

**Comment by fcaviggia** [comment]
Looks like both Unity and Mir are dead - they are planning on dropping support for Unity and Mir in favor of GNOME and Wayland...

http://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-Dropping-Unity

**Comment by fcaviggia** [comment]
This should work in the future with Ubuntu on GNOME and Wayland - I've pretty much tested this on every other WM I could get my hands on including TWM and FVWM.

**Comment by cmschube** [comment]
Fair enough.. Thanks for checking it out!
