### ISSUE TITLE
Lost RHEL6 support

### ISSUE THREAD

**Issue by thomric2** [fcaviggia/classification-banner#24]
With pulling in change #23 python 2.6 is no longer supported breaking native support on RHEL6.

**Comment by thomric2** [comment]
Also that autostart example would need to be changed for the new filename given in #23 as part of the setup.py install process

**Comment by fcaviggia** [comment]
You can still use an older version here:

https://raw.githubusercontent.com/RedHatGov/ssg-el6-kickstart/master/config/hardening/classification-banner.py

**Comment by fcaviggia** [comment]
Red Hat is going to take this into EPEL as a supported package for RHEL.

**Comment by fcaviggia** [comment]
Working on trying to fix issues between RHEL 6/7/8 and Fedora 28

**Comment by fcaviggia** [comment]
Try now - I think I have the issue narrowed down.

**Comment by fcaviggia** [comment]
Thanks. Just fixed it.

**Comment by thomric2** [comment]
Drop the .py extension too

**Comment by fcaviggia** [comment]
Thanks - fixed.
